AWSTemplateFormatVersion: "2010-09-09"

Description: creating S3 Bucket for the lambda function zip code files

Parameters:
  Team:
    Type: String
    Description: the name of the team
    Default: SGB-DevOps

  TeamEmail:
    Type: String
    Description: team e-mail address

  Env:
    Type: String
    Default: dev
    Description: Environment the resources/ stack is deployed to
    AllowedValues:
      - "dev"
      - "sit"
      - "prod"



Resources:
  S3BucketEncryptionLambda:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub lambda-function-s3-${AWS::AccountId}-encryption-python-zipfile-${Env}
      VersioningConfiguration:
        Status: Enabled
     
      Tags:
        - Key: GroupName
          Value: 'SGB-DevOps'
        - Key: Environment
          Value: !Ref Env
        - Key: Team-Email
          Value: 'example@example.com'
        - Key: Tier
          Value: 'MCA'


